apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-jave-web-app
  name: demo-jave-web-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-jave-web-app
  type: LoadBalancer
