name: Demo Java App CI/CD
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Kubectl cli
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.1'
      id: install
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: List Files
      run: ls -la
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: library
        IMAGE_TAG: demo-java-app-v1
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    - name: Update KubeConfig
      run: aws eks update-kubeconfig --name example
    - name: Deploy K8s Resource
      run: kubectl apply -f k8s/.
